name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman Contribution Graph
        uses: Platane/snk@v3
        with:
          github_user_name: yatharthaurangpure01
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push Pacman Animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
