name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman Graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: yatharthaurangpure01
          outputs: |
            dist/pacman.svg?palette=github-dark

      - name: Push Pacman Graph
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
